package springjdbc.entity;

import lombok.*;

import javax.persistence.*;

// named queries can be used more than one time in the code without duplicating the original query
@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Review {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    // Store enum as a string
    @Enumerated(EnumType.STRING)
    private ReviewRating rating;

    @Column(name = "review_body")
    private String description;

    @ManyToOne(fetch = FetchType.LAZY)
    private Course course;

    @ManyToOne(fetch = FetchType.LAZY)
    private Student student;

    // toString autogenerated by Lombok has problems with lazy initialization
    @Override
    public String toString() {
        return "Review{" +
                "rating='" + rating + '\'' +
                ", description='" + description + '\'' +
                '}';
    }
}
